---
abstract: 'Catalyst based application'
author:
  - 'Freya Jarrett'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LolCatalyst-Lite
no_index:
  directory:
    - inc
    - t
requires:
  Acme::Bleach: 0
  Acme::LOLCAT: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::Runtime: 5.7014
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  Config::General: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
